# orchestration_test.toml

# 1) Le metajob de vérification de connexion (avant d'exécuter les autres jobs)
[[jobs]]
name = "metajob"
type = "connection"
#host = "10.0.0.45"
host = "SRVSIG"
port = 5432
retry_interval_min = 5

# 2) Le script Python main.py
[[jobs]]
name = "run_python_main"
type = "python"
#interpreter = "C:\\_sandbox\\dbt-env\\Scripts\\python.exe"
#interpreter_lx = "path/to/linux/interpreter"
script_path = "scripts/main.py"

# 3) Le job dbt
[[jobs]]
name = "run_dbt_debug"
type = "dbt"
cmd = ["dbt", "debug"]


# 4) Le flow principal, qui référence les trois étapes ci-dessus
[[jobs]]
name = "full_flow"
type = "flow"
schedule = "minute_at"
time = ":00"
steps = ["metajob", "run_python_main", "run_dbt_debug"]